// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CarouselClientController from "./carousel_client_controller"
application.register("carousel-client", CarouselClientController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import CarouselSitesController from "./carousel_sites_controller"
application.register("carousel-sites", CarouselSitesController)

import CarouselThumbController from "./carousel_thumb_controller"
application.register("carousel-thumb", CarouselThumbController)

import DropzoneController from "./dropzone_controller"
application.register("dropzone", DropzoneController)

import EmbedController from "./embed_controller"
application.register("embed", EmbedController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import ProcurementsController from "./procurements_controller"
application.register("procurements", ProcurementsController)

import SlideSitesExamplesController from "./slide_sites_examples_controller"
application.register("slide-sites-examples", SlideSitesExamplesController)
